In [69]:
!git clone https://github.com/AshishJangra27/datasets

Cloning into 'datasets'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 328 (delta 19), reused 54 (delta 9), pack-reused 235 (from 1)
Receiving objects: 100% (328/328), 278.62 MiB | 16.50 MiB/s, done.
Resolving deltas: 100% (145/145), done.
Updating files: 100% (225/225), done.


In [1]:
import numpy as np
import pandas as pd

In [20]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(lst)

print(lst)
print(arr)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.random.randint(1,15,(3,4))

print(arr.shape)
arr = arr.reshape(4,3)
print(arr.shape)
arr = arr.reshape(6,2)
print(arr.shape)


arr = arr.reshape(2,6)
print(arr)

(3, 4)
(4, 3)
(6, 2)
[[ 2 10  6  1  6  7]
 [ 1  2  9  8 14 13]]


array([[2, 3, 5, 6],
       [3, 4, 1, 3],
       [3, 3, 1, 4]])

In [30]:
arr = np.array([1,2,31,2,31,23,12,3])


arr[arr > 5]

4

In [25]:
arr = arr * 2

array([ 16,  32, 496,  32, 496, 368, 192,  48])

In [39]:
df = pd.read_csv('/content/airbnb_v2.csv')

df

Unnamed: 0        id  \
0               0  49849504   
1               1  50891766   
2               2  50699164   
3               3  49871422   
4               4  51245886   
...           ...       ...   
12800       12800  44697740   
12801       12801  29975283   
12802       12802  32977697   
12803       12803   8006146   
12804       12804  40547903   

                                                    name rating reviews  \
0                                         Perla bungalov   4.71      64   
1      Authentic Beach Architect Sheltered Villa with...    New       0   
2                                      cottages sataplia   4.85      68   
3                            Sapanca Breathable Bungalow    5.0      13   
4                                          Bungalov Ev 2    New       0   
...                                                  ...    ...     ...   
12800            Brown Dome House No. 3, full of healing   4.94      16   
12801       Bubble Hotel Ubud with Bathtub under the Sky   4.67       6   
12802                                   Paradise Eco Hub   4.67       3   
12803     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86       7   
12804   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85      13   

         host_name      host_id  \
0        Mehmetcan  357334205.0   
1            Fatih  386223873.0   
2           Giorgi  409690853.0   
3            Melih  401873242.0   
4      Arp Sapanca  414884116.0   
...            ...          ...   
12800        Aidan  161552316.0   
12801       Martha  118954227.0   
12802        Silas  175214568.0   
12803      Cempaka     718423.0   
12804         Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
12800  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
12801                                 Gianyar, Indonesia   
12802                                     Kabale, Uganda   
12803        Gunung Sari, Nusa Tenggara Barat, Indonesia   
12804                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
12800                          4 guests,8 bathrooms   
12801     2 guests,1 bedroom,1 bed,Toilet with sink   
12802  2 guests,1 bedroom,2 beds,1 private bathroom   
12803      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
12804          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  ...  price  \
0      Mountain view,Valley view,Lake access,Kitchen,...  ...   8078   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...  ...   4665   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...  ...   5991   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...  ...  11339   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...  ...   6673   
...                                                  ...  ...    ...   
12800  Kitchen,Wifi,Free parking on premises,Private ...  ...   4288   
12801  Wifi,Free on-street parking,Air conditioning,G...  ...  15200   
12802  Wifi,Breakfast,Long-term stays allowed,Unavail...  ...   9103   
12803  Kitchen,Wifi,Dedicated workspace,Free parking ...  ...  42262   
12804  Sea view,Beach access – Beachfront,Kitchen,Wif...  ...   9909   

            country bathrooms  beds guests  toiles  bedrooms  stu

In [48]:
df.describe()

Unnamed: 0            id       host_id         price     bathrooms  \
count  12805.000000  1.280500e+04  1.280500e+04  1.280500e+04  12805.000000   
mean    6402.000000  7.525187e+16  1.638192e+08  1.769780e+04      1.874424   
std     3696.629433  2.007933e+17  1.413622e+08  4.569364e+04      2.091399   
min        0.000000  1.313100e+04  2.303900e+04  3.930000e+02      0.000000   
25%     3201.000000  2.023958e+07  3.700032e+07  3.994000e+03      1.000000   
50%     6402.000000  3.682229e+07  1.256459e+08  8.175000e+03      1.000000   
75%     9603.000000  4.999760e+07  2.639623e+08  1.606200e+04      2.000000   
max    12804.000000  7.017905e+17  4.758973e+08  1.907963e+06     50.000000   

               beds        guests        toiles      bedrooms       studios  
count  12805.000000  12805.000000  12805.000000  12805.000000  12805.000000  
mean       3.316751      5.213745      0.019211      2.136041      0.023585  
std        4.037791      3.808830      0.137272      2.359005      0.151757  
min        0.000000      1.000000      0.000000      0.000000      0.000000  
25%        1.000000      2.000000      0.000000      1.000000      0.000000  
50%        2.000000      4.000000      0.000000      1.000000      0.000000  
75%        4.000000      6.000000      0.000000      3.000000      0.000000  
max       98.000000     16.000000      1.000000     50.000000      1.000000

In [49]:
df.columns

Index(['Unnamed: 0', 'id', 'name', 'rating', 'reviews', 'host_name', 'host_id',
       'address', 'features', 'amenities', 'safety_rules', 'hourse_rules',
       'img_links', 'price', 'country', 'bathrooms', 'beds', 'guests',
       'toiles', 'bedrooms', 'studios', 'checkin', 'checkout'],
      dtype='object')

In [54]:
df['price'].max()

1907963

In [63]:
df[df['country'] == 'India']['price'].mean()

3360.846153846154

In [65]:
df[df['country'] == ' India']['price'].mean()

7556.436008676789

In [68]:
len(df[df['country'] == ' India'])

2766